WebCRUD_PIM_VIII/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebCRUD_PIM_VIII.Models.ViewModels;

namespace WebCRUD_PIM_VIII.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Author()
        {
            return View();
        }

        public IActionResult Project()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebCRUD_PIM_VIII/Controllers/PessoasController.cs
using System.Linq;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebCRUD_PIM_VIII.Data;
using WebCRUD_PIM_VIII.Models;
using WebCRUD_PIM_VIII.Models.ViewModels;

namespace WebCRUD_PIM_VIII.Controllers
{
    public class PessoasController : Controller
    {
        private readonly WebCRUDContext _context;

        public PessoasController(WebCRUDContext context)
        {
            _context = context;
        }

        // GET: Pessoas/Index
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pessoa.ToListAsync());
        }

        // GET: Pessoas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pessoas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Pessoa pessoa)
        {
            PessoaDAO.Insira(pessoa);
            return RedirectToAction(nameof(Index));
        }

        // GET: Pessoas/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Pessoa não encontrada." });
            }

            var obj = await _context.Pessoa
                .FirstOrDefaultAsync(m => m.Id == id);
            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Pessoa não encontrada." });
            }

            Pessoa pessoa = PessoaDAO.Consulte(obj.CPF);

            return View(pessoa);
        }

        // GET: Pessoas/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Pessoa não encontrada." });
            }

            var obj = await _context.Pessoa.FindAsync(id);
            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Pessoa não encontrada." });
            }

            Pessoa pessoa = PessoaDAO.Consulte(obj.CPF);

            return View(pessoa);
        }

        // POST: Pessoas/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,CPF,Endereco,Telefones")] Pessoa pessoa)
        {
            if (id != pessoa.Id)
            {
                return RedirectToAction(nameof(Error), new { message = "Pessoa não encontrada." });
            }

            if (ModelState.IsValid)
            {
                try
                {
                    PessoaDAO.Altere(pessoa);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PessoaExists(pessoa.Id))
                    {
                        return RedirectToAction(nameof(Error), new { message = "Pessoa não encontrada." });
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pessoa);
        }

        // GET: Pessoas/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Pessoa não encontrada." });
            }

            var obj = await _context.Pessoa
                .FirstOrDefaultAsync(m => m.Id == id);
            if (obj == null)
            {
                return RedirectToAction(nameof(Error), new { message = "Pessoa não encontrada." });
            }

            Pessoa pessoa = PessoaDAO.Consulte(obj.CPF);

            return View(pessoa);
        }

        // POST: Pessoas/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pessoa = await _context.Pessoa.FindAsync(id);
            PessoaDAO.Exclua(PessoaDAO.Consulte(pessoa.CPF));
            return RedirectToAction(nameof(Index));
        }

        private bool PessoaExists(int id)
        {
            return _context.Pessoa.Any(e => e.Id == id);
        }

        // Método de busca que apresenta os datalhes do CPF pesquisado.
        public IActionResult Search(long cpf)
        {
            Pessoa pessoa = PessoaDAO.Consulte(cpf);

            if (pessoa.Id == 0)
            {
                return RedirectToAction(nameof(Error), new { message = "Pessoa não encontrada." });
            }

            return View("Details", pessoa);
        }

        //Método que redireciona o usuário para página de erro.
        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel 
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                Message = message
            };
            return View(viewModel);
        }
    }
}

WebCRUD_PIM_VIII/Views/Home/Author.cshtml
@{
    ViewData["Title"] = "Gabriel Rodrigues de Moraes";
}
<h1>@ViewData["Title"]</h1>

<p style="margin-top: 30px"><font size="5">Aluno de Análise e Desenvolvimento de Sistemas na Universidade Paulista.</font></p>

<div class="row container">
    <div class="img">
        <img src="~/images/author.jpg" height="350" width="275"/>
    </div>
    <div>
        <div style="margin-top: 20px">
            <p style="margin-left: 30px"><font size="5">Campinas - SP | 22/03/1985</font></p>
        </div>
        <div style="margin-top: 40px">
            <p style="margin-left: 30px"><font size="5">Estagiário de desenvolvimento de softwares na IBM, em</font></p>
            <p style="margin-left: 30px"><font size="5">início de sua carreira tecnológica após 10 anos de</font></p>
            <p style="margin-left: 30px"><font size="5">trabalho no ramo da aviação civil.</font></p>
        </div>
    </div>
</div>


<p style="margin-top: 30px"><font size="5"><a href="https://www.linkedin.com/in/gabrielmoraes-br/" target="_blank" rel="noopener noreferrer">LinkedIn</a> | 
    <a href="https://www.credly.com/users/gabrielmoraes-br/badges" target="_blank" rel="noopener noreferrer">Creadly</a> | 
    <a href="https://github.com/gabrielmoraes-br" target="_blank" rel="noopener noreferrer">GitHub</a> | 
    <a href="https://www.instagram.com/gabrielmoraes.br/" target="_blank" rel="noopener noreferrer">Instagram</a></font></p>

<p style="margin-top: 60px"><font size="3"><a asp-action="">Voltar para a página inicial</a>.</font></p>

WebCRUD_PIM_VIII/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" style="margin: 80px">
    <h1 class="display-4">Aplicação ASP.NET para CRUD em Banco de Dados MySQL</h1>
    <p style="margin-top: 60px"><font size="5">Saiba mais sobre o <a asp-action="Author">autor</a> e este <a asp-action="Project">projeto</a>.</font></p>

    <a style="margin-top: 60px" class="btn btn-primary col-md-4" asp-area="" asp-controller="Pessoas" asp-action="Index">Cadastro de Pessoas</a>
</div>

WebCRUD_PIM_VIII/Views/Home/Project.cshtml
@{
    ViewData["Title"] = "O Projeto";
}
<h1>@ViewData["Title"]</h1>

<p style="margin-top: 30px"><font size="5">Aplicação ASP.NET MVC para CRUD em Banco de Dados MySQL.</font></p>


<div class="row container">
    <div>
        <img src="~/images/diagrama-classes.jpg" height="510" width="690"/>
    </div>
    <div>
        <div>
            <p style="margin-left: 10px"><font size="4">Fonte: UNIP - Diagrama de classes.</font></p>
        </div>
        <div style="margin-top: 40px">
            <p><font size="5">O projeto consiste de um CRUD que utiliza uma classe DAO para a</font></p>
            <p><font size="5">manipulação total das funções nas tabelas do banco de dados SQL:</font></p>
        </div>
    </div>
    <div>
        <img src="~/images/diagrama-db.jpg" height="280" width="680"/>
    </div>
    <div>
        <div>
            <p style="margin-left: 10px"><font size="4">Fonte: UNIP - Diagrama Entidade-Relacionamento do Banco de Dados.</font></p>
        </div>
        <div style="margin-top: 40px">
            <p><font size="5">O objetivo foi construir este mecanismo de acesso para a execução</font></p>
            <p><font size="5">de cadastros de pessoas usando um formulário completo de dados.</font></p>
        </div>
    </div>
</div>

<p style="margin-top: 20px"><font size="3"><a asp-action="">Voltar para a página inicial</a>.</font></p>